### ISSUE TITLE
Add hover styling to post button

### ISSUE THREAD

**Issue by eeels22** [NeuralAlchemist/cuddly#32]
Perhaps add box shadow or other styling when you hover over the post button to indicate it is a link (PostCard.jsx)

![Screenshot 2021-05-06 at 11 21 09](https://user-images.githubusercontent.com/46404690/117274257-3045bb80-ae5d-11eb-968f-5b3c423443f2.png)

**Comment by NeuralAlchemist** [comment]
5bedf543e687fe3ef4f2f5dc4c535480c8d9e993 fixes this
