### ISSUE TITLE
Uploading the same video, display a blank home page

### ISSUE THREAD

**Issue by deciocandido** [NeuralAlchemist/cuddly#59]
<img width="1179" alt="Screenshot 2021-05-13 at 11 48 13" src="https://user-images.githubusercontent.com/51098348/118109173-2255e480-b3e1-11eb-82e6-ecd256a3ed93.png">

**Comment by NeuralAlchemist** [comment]
I was unable to replicate this issues, unsure if it got fixed somewhere along the way "accidentally".
