### ISSUE TITLE
comments with large images sometimes need page reloaded manually to show the updated changes

### ISSUE THREAD

**Issue by NeuralAlchemist** [NeuralAlchemist/cuddly#74]
Eg. fox-on-the-run(7~ MB) image failed to show the updated changes immediately a few times. However had no trouble with large VIDEO files (9.4 MB)

**Comment by eeels22** [comment]
Mine has a delay of a few seconds but does eventually load (roughly 5 seconds from pressing 'post' to the post appearing)

**Comment by NeuralAlchemist** [comment]
closing this issues as its not very consistent
