### ISSUE TITLE
Call setContentText only on submit

### ISSUE THREAD

**Issue by eeels22** [NeuralAlchemist/cuddly#8]
will this update the contentText for every time a change occurs? If so is it at all possible to update it only on submit?

_Originally posted by @NeuralAlchemist in https://github.com/NeuralAlchemist/cuddly/pull/6#r622049054_

**Comment by eeels22** [comment]
onChange only occurs after the `textarea` loses focus: https://www.w3schools.com/jsref/event_onchange.asp, so the user would need to click away before `setContentText` is called

**Comment by NeuralAlchemist** [comment]
think this is not necessary anymore as we actually use the contentText to dynamically updated the character limit. Closing with this comment.
